config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "users/sign_in" => "sessions#new"
  post "users/sign_in" => "sessions#create"

  root to: "chat_rooms#index"
  resources :chat_rooms, only: [:index, :show] do
    resources :chat_messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
# == Schema Information
#
# Table name: chat_messages
#
#  id           :bigint           not null, primary key
#  message      :text             not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  chat_room_id :bigint           not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_chat_messages_on_chat_room_id  (chat_room_id)
#  index_chat_messages_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (chat_room_id => chat_rooms.id)
#  fk_rails_...  (user_id => users.id)
#
class ChatMessage < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user

  validates :message, presence: true
end

app/models/chat_room.rb
# == Schema Information
#
# Table name: chat_rooms
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_chat_rooms_on_name  (name) UNIQUE
#
class ChatRoom < ApplicationRecord
  has_many :chat_messages, dependent: :destroy
  has_many :chat_room_members, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/chat_room_member.rb
# == Schema Information
#
# Table name: chat_room_members
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  chat_room_id :bigint           not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_chat_room_members_on_chat_room_id  (chat_room_id)
#  index_chat_room_members_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (chat_room_id => chat_rooms.id)
#  fk_rails_...  (user_id => users.id)
#
class ChatRoomMember < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  nickname   :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_users_on_nickname  (nickname) UNIQUE
#
class User < ApplicationRecord
  has_many :chat_messages, dependent: :destroy
  has_many :chat_room_members, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_members

  # あくまでチャットアプリのサンプルなのでログイン機構は省略
  validates :nickname, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_user!
    if session[:user_id].nil?
      redirect_to users_sign_in_path
      return
    end

    @current_user = User.find(session[:user_id])
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @chat_room = current_user.chat_rooms.find(params[:chat_room_id])
    @chat_message = @chat_room.chat_messages.build(chat_message_params)
    @chat_message.user = current_user

    if @chat_message.save
      render "chat_rooms/create_chat_message_success"
    else
      @chat_messages = @chat_room.chat_messages
      render "chat_rooms/create_chat_message_failure", status: :unprocessable_entity
    end
  end

  private

    def chat_message_params
      params.require(:chat_message).permit(:message)
    end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat_rooms = current_user.chat_rooms
  end

  def show
    @chat_room = current_user.chat_rooms.find(params[:id])
    @chat_messages = @chat_room.chat_messages
    @chat_message = @chat_room.chat_messages.build
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @users = User.all
  end

  def create
    @user = User.find(params[:user_id])
    session[:user_id] = @user.id
    redirect_to root_url
  end
end

app/views/chat_rooms/_chat_message.html.erb
<div>
  <%= chat_message.user.nickname %>
  <br>
  <%= chat_message.message %>
</div>

app/views/chat_rooms/_chat_message_form.erb
<%= form_with model: chat_message, url: chat_room_chat_messages_path(chat_room) do |f| %>
  <% chat_message.errors.full_messages.each do |error_message| %>
    <div><%= error_message %></div>
  <% end %>

  <%= f.text_field :message %>
  <%= f.submit "送信" %>
<% end %>

app/views/chat_rooms/create_chat_message_failure.turbo_stream.erb
<%= turbo_stream.update "chat-message-form", partial: "chat_rooms/chat_message_form", locals: { chat_message: @chat_message, chat_room: @chat_room } %>

app/views/chat_rooms/create_chat_message_success.turbo_stream.erb
<%= turbo_stream.update "chat-message-form", partial: "chat_rooms/chat_message_form", locals: { chat_message: @chat_room.chat_messages.build, chat_room: @chat_room } %>
<% @chat_message.broadcast_append_to("chat_room_#{@chat_room.id}", target: "chat-messages", partial: "chat_rooms/chat_message") %>

app/views/chat_rooms/index.html.erb
<% @chat_rooms.each do |chat_room| %>
  <div>
    <%= link_to chat_room.name, chat_room_path(chat_room) %>
  </div>
<% end %>

app/views/chat_rooms/show.html.erb
<%= link_to "チャットルーム一覧", chat_rooms_path %>

<h1><%= @chat_room.name %></h1>

<%= turbo_stream_from "chat_room_#{@chat_room.id}" %>

<div id="chat-messages">
  <% @chat_messages.each do |chat_message| %>
    <% next unless chat_message.persisted? %>

    <%= render "chat_message", chat_message: %>
  <% end %>
</div>

<div id="chat-message-form">
  <%= render "chat_message_form", chat_message: @chat_message, chat_room: @chat_room %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRealtimeChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>